language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
install:
  - yarn install
script:
  - yarn lerna run lint
  - yarn lerna run test
  - yarn lerna run build
after_success:
  - test $TRAVIS_BRANCH = "master" && test $TRAVIS_PULL_REQUEST = "false" && yarn lerna publish --conventional-commits --yes
