language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.13.0
  - export PATH="$HOME/.yarn/bin:$PATH"
install:
  - yarn install --frozen-lockfile
script:
  - bin/build
before_deploy:
  - bin/before-deploy
deploy:
  skip_cleanup: true
  provider: script
  script: bin/deploy
  on:
    branch: master
