language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
install:
  - yarn install
script:
<<<<<<< HEAD
  - yarn lerna run lint
  - yarn lerna run test
  - yarn lerna run build
before_deploy:
  - git config --global user.email ${GITHUB_EMAIL}
  - git config --global user.name ${GITHUB_USER}
  - git checkout master
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" >> $HOME/.npmrc 2> /dev/null
deploy:
  skip_cleanup: true
  provider: script
  script: 'yarn lerna publish --conventional-commits --yes'
=======
  - bin/build
before_deploy:
  - bin/before-deploy
deploy:
  skip_cleanup: true
  provider: script
  script: bin/deploy
>>>>>>> chore(ci): add commitlint step to ci
  on:
    branch: master
