language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
install:
  - yarn install
script:
  - bin/build
before_deploy:
  - bin/before-deploy
deploy:
  skip_cleanup: true
  provider: script
  script: bin/deploy
  on:
    branch: master
